spring.application.name=job-lyrics-sync
#Job
job.lyrics.path-scanner=job-lyrics-sync/lyrics/input
job.lyrics.output-meta-data=job-lyrics-sync/output_metadata
#Log
logging.file.path=/job-lyrics-sync/log
logging.file.name=job-lyrics-sync.log
logging.level.nd.mahn.lyricssync=DEBUG